spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/
    locations: classpath:db/migration
logging:
  level:
    root: DEBUG

server:
  port: 8083
