spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}/social_users
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST}/social_users
    locations: classpath:db/migration

server:
  port: 8081
