spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5454/social_posts
    username: crc
    password: crc
  flyway:
    url: jdbc:postgresql://localhost:5454/social_posts
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      post: 6379


server:
  port: 8082

destinations:
  queues:
    OTUS_POSTS_UPDATE:
      exchange: POSTS_UPDATE
      routing-key: UPDATE
