spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}/social_posts
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST}/social_posts
    locations: classpath:db/migration

  rabbitmq:
    host: ${BROKER_HOST}
    port: ${BROKER_PORT}
    username: ${BROKER_USER}
    password: ${BROKER_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      post: ${REDIS_PORT}

server:
  port: 8082

destinations:
  queues:
    OTUS_POSTS_UPDATE:
      exchange: POSTS_UPDATE
      routing-key: UPDATE
