spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}/social_counter
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST}/social_counter
    locations: classpath:db/migration

  rabbitmq:
    host: ${BROKER_HOST}
    port: ${BROKER_PORT}
    username: ${BROKER_USER}
    password: ${BROKER_PASSWORD}

server:
  port: 8085

destinations:
  queues:
    OTUS_POSTS_COUNTER:
      exchange: POSTS_COUNTER
      routing-key: UPDATE
    OTUS_POSTS_COUNTER_APPROVE:
      exchange: POSTS_COUNTER
      routing-key: APPROVE
